name: 'jobs_data_platform'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  jobs_data_platform:
    staging:
      +schema: staging
      +materialized: view
      +tags: ['daily']
    int:
      +schema: int
      +materialized: table
      +tags: ['daily']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['daily']
    analysis:
      +schema: analysis
      +materialized: table
      +tags: ['daily']
    reporting:
      +schema: reporting
      +materialized: table
      +tags: ['daily']
    exports:
      +schema: exports
      +materialized: view
      +tags: ['daily']

seeds: 
  jobs_data_platform:
    +schema: seeds
    serpapi_query_versions:
      +column_types:
        query_id: integer
        q: string
        location: string
        hl: string
        gl: string
        max_jobs: integer
        google_domain: string
        active: integer
