version: 2

sources:
  - name: jobs_scraping
    database: "{{ env_var('DBT_GCP_PROJECT', 'projects-portfolio-446806') }}" # GCP project id
    schema: jobs_scraping                   # BigQuery dataset
    tables:
      - name: linkedin_scraped_jobs
      - name: serpapi_jobs
        config:
          loaded_at_field: created_at
          freshness:
            warn_after: {count: 75, period: hour}
