version: 2

sources:
  - name: personal_finance
    database: "{{ env_var('DBT_GCP_PROJECT', 'projects-portfolio-446806') }}" # GCP project id
    schema: personal_finance                   
    tables:
      - name: accounts
      - name: bsa_balances
      - name: budgets
      - name: categories
      - name: manual_transactions
      - name: plaid_transactions
      - name: retirement_ledger
      
