version: 2

sources:
  - name: tesla_data_platform
    database: "{{ env_var('DBT_GCP_PROJECT', 'dev-projects-portfolio') }}" # projects-portfolio-446806     # GCP project id
    schema: tesla_data_platform                   
    tables:
      - name: vehicle_info
      - name: app_users
      - name: app_vehicles
      - name: service_records
